import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * 가이드 사이드바 — 4개 로케일 모두 동일 구조.
 * 항목 라벨은 각 로케일의 docs frontmatter sidebar_label 로 자동 번역됨.
 * (Docusaurus 가 doc id → 현재 로케일의 frontmatter 라벨로 치환)
 *
 * API 섹션은 autogenerated — scripts/gen-api.mjs 가
 * docs/api/_category_.json 과 api/*.md 를 생성한다.
 */
const sidebars: SidebarsConfig = {
  guide: [
    {
      type: 'category',
      label: '시작하기',
      collapsed: false,
      items: [
        'index',
        'guide/installation',
        'guide/getting-started',
      ],
    },
    {
      type: 'category',
      label: 'DI 시스템',
      items: [
        'guide/di/index',
        'guide/di/installer',
        'guide/di/locator',
        'guide/di/lifecycle',
      ],
    },
    {
      type: 'category',
      label: '매니저 시스템',
      items: [
        'guide/managers/index',
        'guide/managers/config',
        'guide/managers/audio',
        'guide/managers/scene',
        'guide/managers/pool',
        'guide/managers/player-data',
        'guide/managers/iap',
      ],
    },
    {
      type: 'category',
      label: 'UI 시스템',
      items: [
        'guide/ui/index',
        'guide/ui/views',
        'guide/ui/workspace',
        'guide/ui/binding',
        'guide/ui/draggable',
        'guide/ui/red-dot',
        'guide/ui/button-extras',
      ],
    },
    {
      type: 'category',
      label: 'Table Loader',
      items: [
        'guide/table/index',
        'guide/table/setup',
        'guide/table/json-to-csv',
        'guide/table/codegen',
      ],
    },
    {
      type: 'category',
      label: 'Localization',
      items: [
        'guide/localization/index',
        'guide/localization/setup',
        'guide/localization/codegen',
      ],
    },
    {
      type: 'category',
      label: 'Addressables',
      items: [
        'guide/addressables/index',
        'guide/addressables/folders',
        'guide/addressables/remote',
      ],
    },
    {
      type: 'category',
      label: '게임플레이',
      items: [
        'guide/movement',
        'guide/pathfinding',
        'guide/ecs/index',
      ],
    },
    {
      type: 'category',
      label: '비동기 & 네트워크',
      items: [
        'guide/async',
        'guide/timer',
        'guide/debug-console',
        'guide/web-request',
      ],
    },
    {
      type: 'category',
      label: '유틸리티',
      items: [
        'guide/singleton/index',
        'guide/extensions/index',
        'guide/extensions/scriptable-object',
      ],
    },
    {
      type: 'category',
      label: '부록',
      items: [
        'guide/integration',
        'changelog',
      ],
    },
    {
      type: 'category',
      label: 'API 레퍼런스',
      collapsed: true,
      link: { type: 'doc', id: 'api/index' },
      // docs/api/ 아래의 모든 폴더와 파일을 자동 트리로 펼침
      // (gen-api.mjs 가 폴더별 _category_.json 으로 라벨/순서 제어)
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],
};

export default sidebars;
