using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

namespace AchEngine.Localization.Editor
{
    /// <summary>
    /// LocaleDatabase의 키를 기반으로 타입 안전한 상수 클래스를 생성.
    /// dot-notation 키를 중첩 static class로 변환.
    /// 예: "menu.start" → L.Menu.Start
    /// </summary>
    public static class LocalizationKeyGenerator
    {
        // C# 예약 키워드 목록
        private static readonly HashSet<string> CSharpKeywords = new HashSet<string>
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
            "checked", "class", "const", "continue", "decimal", "default", "delegate",
            "do", "double", "else", "enum", "event", "explicit", "extern", "false",
            "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
            "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
            "new", "null", "object", "operator", "out", "override", "params", "private",
            "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
            "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
            "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
            "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
        };

        /// <summary>
        /// 설정에 따라 키 상수 클래스를 생성
        /// </summary>
        public static void Generate(LocalizationSettings settings)
        {
            if (settings == null) throw new ArgumentNullException(nameof(settings));
            if (settings.database == null)
                throw new InvalidOperationException("LocaleDatabase가 설정되지 않았습니다.");

            settings.database.InvalidateCache();
            settings.database.ParseJsonAssets();

            var allKeys = settings.database.GetAllKeys();
            string className = string.IsNullOrWhiteSpace(settings.generatedClassName) ? "L" : settings.generatedClassName.Trim();
            string ns = settings.generatedNamespace;
            string outputPath = settings.generatedOutputPath;

            if (string.IsNullOrWhiteSpace(outputPath))
                throw new InvalidOperationException("생성 코드 출력 경로가 비어 있습니다.");

            string code = GenerateCode(allKeys, className, ns);
            string filePath = Path.Combine(outputPath, $"{SanitizeIdentifier(className)}.cs");

            LocalizationEditorUtility.EnsureDirectoryExists(outputPath);
            File.WriteAllText(Path.GetFullPath(filePath), code, Encoding.UTF8);
            AssetDatabase.ImportAsset(filePath);

            UnityEngine.Debug.Log($"[Localization] 키 상수 생성 완료: {filePath} ({allKeys.Count}개)");
        }

        /// <summary>
        /// 키 목록으로부터 C# 소스 코드 생성
        /// </summary>
        internal static string GenerateCode(List<string> keys, string className, string ns)
        {
            if (keys == null) throw new ArgumentNullException(nameof(keys));
            if (string.IsNullOrWhiteSpace(className))
                throw new ArgumentException("생성 클래스 이름은 비어 있을 수 없습니다.", nameof(className));
            ValidateNamespace(ns);

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Achieve Localization이 자동 생성한 파일입니다. 직접 수정하지 마세요.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrWhiteSpace(ns);
            string indent = hasNamespace ? "    " : "";

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }

            // 키를 트리 구조로 변환
            var root = BuildKeyTree(keys);
            ValidateMemberCollisions(root, "root");

            // 루트 클래스 생성
            GenerateClass(sb, className, root, indent);

            if (hasNamespace)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static KeyNode BuildKeyTree(List<string> keys)
        {
            var root = new KeyNode();

            foreach (var key in keys)
            {
                if (string.IsNullOrWhiteSpace(key))
                    throw new ArgumentException("로컬라이제이션 키는 비어 있을 수 없습니다.", nameof(keys));

                var segments = key.Split('.');
                if (segments.Any(string.IsNullOrWhiteSpace))
                    throw new InvalidOperationException($"키 '{key}'에 비어 있는 경로 구간이 있습니다.");

                if (segments.Length == 1)
                {
                    // dot이 없는 단순 키
                    root.Values[key] = key;
                }
                else
                {
                    // dot으로 구분된 키 → 중첩 구조
                    var current = root;
                    for (int i = 0; i < segments.Length - 1; i++)
                    {
                        string segment = segments[i];
                        if (!current.Children.TryGetValue(segment, out var child))
                        {
                            child = new KeyNode();
                            current.Children[segment] = child;
                        }
                        current = child;
                    }

                    // 마지막 세그먼트는 값
                    string lastSegment = segments[segments.Length - 1];
                    current.Values[lastSegment] = key;
                }
            }

            return root;
        }

        private static void GenerateClass(StringBuilder sb, string className, KeyNode node, string indent)
        {
            sb.AppendLine($"{indent}public static class {SanitizeIdentifier(className)}");
            sb.AppendLine($"{indent}{{");

            string innerIndent = indent + "    ";

            // 값(const string) 생성
            foreach (var kvp in node.Values.OrderBy(k => k.Key, StringComparer.Ordinal))
            {
                string fieldName = ToPascalCase(kvp.Key);
                fieldName = SanitizeIdentifier(fieldName);
                sb.AppendLine($"{innerIndent}public const string {fieldName} = \"{EscapeString(kvp.Value)}\";");
            }

            // 자식 클래스 생성
            bool firstChild = true;
            foreach (var kvp in node.Children.OrderBy(k => k.Key, StringComparer.Ordinal))
            {
                if (node.Values.Count > 0 || !firstChild)
                    sb.AppendLine();
                firstChild = false;

                GenerateClass(sb, ToPascalCase(kvp.Key), kvp.Value, innerIndent);
            }

            sb.AppendLine($"{indent}}}");
        }

        private static string ToPascalCase(string input)
        {
            if (string.IsNullOrEmpty(input))
                return "_";

            var sb = new StringBuilder();
            bool capitalizeNext = true;

            foreach (char c in input)
            {
                if (c == '_' || c == '-' || c == ' ')
                {
                    capitalizeNext = true;
                    continue;
                }

                if (capitalizeNext)
                {
                    sb.Append(char.ToUpperInvariant(c));
                    capitalizeNext = false;
                }
                else
                {
                    sb.Append(c);
                }
            }

            return sb.Length > 0 ? sb.ToString() : "_";
        }

        private static string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name))
                return "_";

            // 숫자로 시작하면 _ 접두사
            if (char.IsDigit(name[0]))
                name = "_" + name;

            // 특수문자를 _ 로 치환
            var sb = new StringBuilder();
            foreach (char c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }

            string result = sb.ToString();

            // C# 예약어 충돌
            if (CSharpKeywords.Contains(result.ToLowerInvariant()))
                result = "@" + result;

            return result;
        }

        private static string EscapeString(string value)
        {
            if (value == null) return string.Empty;

            var sb = new StringBuilder(value.Length);
            foreach (var character in value)
            {
                switch (character)
                {
                    case '"': sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\b': sb.Append("\\b"); break;
                    case '\f': sb.Append("\\f"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default:
                        if (character < ' ')
                            sb.Append($"\\u{(int)character:x4}");
                        else
                            sb.Append(character);
                        break;
                }
            }
            return sb.ToString();
        }

        private static void ValidateNamespace(string ns)
        {
            if (string.IsNullOrWhiteSpace(ns)) return;

            foreach (var segment in ns.Split('.'))
            {
                if (string.IsNullOrWhiteSpace(segment) || SanitizeIdentifier(segment) != segment)
                    throw new ArgumentException($"네임스페이스 '{ns}'이(가) 올바른 C# 식별자가 아닙니다.", nameof(ns));
            }
        }

        private static void ValidateMemberCollisions(KeyNode node, string path)
        {
            var generatedNames = new Dictionary<string, string>(StringComparer.Ordinal);

            foreach (var value in node.Values)
            {
                string generatedName = SanitizeIdentifier(ToPascalCase(value.Key));
                AddGeneratedName(generatedNames, generatedName, value.Key, path);
            }

            foreach (var child in node.Children)
            {
                string generatedName = SanitizeIdentifier(ToPascalCase(child.Key));
                AddGeneratedName(generatedNames, generatedName, child.Key, path);
                ValidateMemberCollisions(child.Value, $"{path}.{generatedName}");
            }
        }

        private static void AddGeneratedName(
            IDictionary<string, string> generatedNames,
            string generatedName,
            string sourceName,
            string path)
        {
            if (generatedNames.TryGetValue(generatedName, out var existing))
                throw new InvalidOperationException(
                    $"키 이름 충돌: '{existing}'과(와) '{sourceName}'이(가) 모두 '{path}.{generatedName}'으로 생성됩니다.");

            generatedNames[generatedName] = sourceName;
        }

        private class KeyNode
        {
            public Dictionary<string, string> Values = new Dictionary<string, string>(StringComparer.Ordinal);
            public Dictionary<string, KeyNode> Children = new Dictionary<string, KeyNode>(StringComparer.Ordinal);
        }
    }
}
