using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

namespace AchEngine.Localization.Editor
{
    /// <summary>
    /// LocaleDatabase의 키를 기반으로 타입 안전한 상수 클래스를 생성.
    /// dot-notation 키를 중첩 static class로 변환.
    /// 예: "menu.start" → L.Menu.Start
    /// </summary>
    public static class LocalizationKeyGenerator
    {
        // C# 예약 키워드 목록
        private static readonly HashSet<string> CSharpKeywords = new HashSet<string>
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
            "checked", "class", "const", "continue", "decimal", "default", "delegate",
            "do", "double", "else", "enum", "event", "explicit", "extern", "false",
            "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
            "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
            "new", "null", "object", "operator", "out", "override", "params", "private",
            "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
            "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
            "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
            "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
        };

        /// <summary>
        /// 설정에 따라 키 상수 클래스를 생성
        /// </summary>
        public static void Generate(LocalizationSettings settings)
        {
            if (settings?.database == null) return;

            settings.database.InvalidateCache();
            settings.database.ParseJsonAssets();

            var allKeys = settings.database.GetAllKeys();
            string className = string.IsNullOrWhiteSpace(settings.generatedClassName) ? "L" : settings.generatedClassName;
            string ns = settings.generatedNamespace;
            string outputPath = settings.generatedOutputPath;

            string code = GenerateCode(allKeys, className, ns);
            string filePath = Path.Combine(outputPath, $"{className}.cs");

            LocalizationEditorUtility.EnsureDirectoryExists(outputPath);
            File.WriteAllText(Path.GetFullPath(filePath), code, Encoding.UTF8);
            AssetDatabase.ImportAsset(filePath);

            UnityEngine.Debug.Log($"[Localization] Generated key constants: {filePath} ({allKeys.Count} keys)");
        }

        /// <summary>
        /// 키 목록으로부터 C# 소스 코드 생성
        /// </summary>
        internal static string GenerateCode(List<string> keys, string className, string ns)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Achieve Localization. Do not edit manually.");
            sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrWhiteSpace(ns);
            string indent = hasNamespace ? "    " : "";

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }

            // 키를 트리 구조로 변환
            var root = BuildKeyTree(keys);

            // 루트 클래스 생성
            GenerateClass(sb, className, root, indent);

            if (hasNamespace)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static KeyNode BuildKeyTree(List<string> keys)
        {
            var root = new KeyNode { Name = "root" };

            foreach (var key in keys)
            {
                var segments = key.Split('.');

                if (segments.Length == 1)
                {
                    // dot이 없는 단순 키
                    root.Values[key] = key;
                }
                else
                {
                    // dot으로 구분된 키 → 중첩 구조
                    var current = root;
                    for (int i = 0; i < segments.Length - 1; i++)
                    {
                        string segment = segments[i];
                        if (!current.Children.TryGetValue(segment, out var child))
                        {
                            child = new KeyNode { Name = segment };
                            current.Children[segment] = child;
                        }
                        current = child;
                    }

                    // 마지막 세그먼트는 값
                    string lastSegment = segments[segments.Length - 1];
                    current.Values[lastSegment] = key;
                }
            }

            return root;
        }

        private static void GenerateClass(StringBuilder sb, string className, KeyNode node, string indent)
        {
            sb.AppendLine($"{indent}public static class {SanitizeIdentifier(className)}");
            sb.AppendLine($"{indent}{{");

            string innerIndent = indent + "    ";

            // 값(const string) 생성
            foreach (var kvp in node.Values.OrderBy(k => k.Key))
            {
                string fieldName = ToPascalCase(kvp.Key);
                fieldName = SanitizeIdentifier(fieldName);
                sb.AppendLine($"{innerIndent}public const string {fieldName} = \"{EscapeString(kvp.Value)}\";");
            }

            // 자식 클래스 생성
            bool firstChild = true;
            foreach (var kvp in node.Children.OrderBy(k => k.Key))
            {
                if (node.Values.Count > 0 || !firstChild)
                    sb.AppendLine();
                firstChild = false;

                GenerateClass(sb, ToPascalCase(kvp.Key), kvp.Value, innerIndent);
            }

            sb.AppendLine($"{indent}}}");
        }

        private static string ToPascalCase(string input)
        {
            if (string.IsNullOrEmpty(input))
                return "_";

            var sb = new StringBuilder();
            bool capitalizeNext = true;

            foreach (char c in input)
            {
                if (c == '_' || c == '-' || c == ' ')
                {
                    capitalizeNext = true;
                    continue;
                }

                if (capitalizeNext)
                {
                    sb.Append(char.ToUpperInvariant(c));
                    capitalizeNext = false;
                }
                else
                {
                    sb.Append(c);
                }
            }

            return sb.Length > 0 ? sb.ToString() : "_";
        }

        private static string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name))
                return "_";

            // 숫자로 시작하면 _ 접두사
            if (char.IsDigit(name[0]))
                name = "_" + name;

            // 특수문자를 _ 로 치환
            var sb = new StringBuilder();
            foreach (char c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }

            string result = sb.ToString();

            // C# 예약어 충돌
            if (CSharpKeywords.Contains(result.ToLowerInvariant()))
                result = "@" + result;

            return result;
        }

        private static string EscapeString(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private class KeyNode
        {
            public string Name;
            public Dictionary<string, string> Values = new Dictionary<string, string>();
            public Dictionary<string, KeyNode> Children = new Dictionary<string, KeyNode>();
        }
    }
}
